feat: Migrate ds-controller microservice to EdgeX 3.0
intel-retail/automated-vending pull request #145
Opened 2023-09-19 22:56 UTC by NeethuES-intel

## PR Checklist

- [X] Added label to the Pull Request for easier discoverability and search
- [X] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-vending/blob/main/.github/CONTRIBUTING.md
- [X] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [X] All commented out code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

## Issue this PR will close

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable
Run the following make commands from the ds-controller directory, all should run without erros

- make docker
- make test

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-vending )

2023-09-19 23:16 UTC, jim-wang-intel approved these changes
LGTM

2023-09-19 23:58 UTC, lenny-intel approved these changes
LGTM

2023-09-20 00:30 UTC, lenny-intel requested changes
Still need to convert the res/devices/device-list.toml to yaml

2023-09-20 17:38 UTC, lenny-intel requested changes

2023-09-20 17:38 UTC, lenny-intel commented on ds-controller-board/res/devices/device-list.yaml
> +      onChange: true
Indentation in TOML we off . I matter in YAML, but not in TOML.
```suggestion
  protocols: 
  autoEvents:
    interval: 3s
    onChange: true
```

2023-09-20 17:59 UTC, merged