feat: update docs for edgex 3.0 update
intel-retail/automated-vending pull request #152
Opened 2023-09-26 21:06 UTC by vli11

Closes: #137

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-vending/blob/main/.github/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [x] Updated Documentation as relevant to the changes
- [ ] All commented out code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?
update automated checking to automated vending; updated toml file to yaml file and their new links.

## Issue this PR will close

close: #137 

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable
read through the docs_src folder, all automated checkout should be replaced, and no more toml file

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-vending )

2023-09-26 21:30 UTC, jim-wang-intel requested changes
there are some url still pointing to the old url (intel-iot-devkit) and /v2 to /v3
please do a global search under docs/src folder to fix them all.

2023-09-26 21:30 UTC, jim-wang-intel commented on docs_src/automated-vending-services/device_services.md
>  | Inference/CommandTopic                  | All events pushed from EdgeX's command API are fed into this topic. The [`as-vending`](https://github.com/intel-iot-devkit/automated-checkout/blob/master/a
we probably also want to fix the url for that too: 
```suggestion
| Inference/CommandTopic                  | All events pushed from EdgeX's command API are fed into this topic. The [`as-vending`](https://github.com/intel-retail/automated-vending/tree/main/as-vending) and [`as-controller-board-status`](https://github.com/intel-retail/automated-vending/tree/main/as-controller-board-status) are two services that make requests to this API, typically for making door close/open and heartbeat events. |
```

2023-09-26 21:30 UTC, jim-wang-intel commented on docs_src/automated-vending-services/device_services.md
>  | Inference/DataTopic                | The cv inference service publishes delta SKUs on this topic, then the MQTT device service converts them into EdgeX event readings, and finally the [`as-vending`
```suggestion
| Inference/DataTopic                | The cv inference service publishes delta SKUs on this topic, then the MQTT device service converts them into EdgeX event readings, and finally the [`as-vending`](https://github.com/intel-retail/automated-vending/tree/main/as-vending) service processes the event readings and pushes them to downstream services. |
```

2023-09-26 21:30 UTC, jim-wang-intel commented on docs_src/automated-vending-services/device_services.md
>  #### `GET`: `http://localhost:59982/api/v2/device/name/Inference-device/inferenceHeartbeat`
```suggestion
#### `GET`: `http://localhost:59982/api/v3/device/name/Inference-device/inferenceHeartbeat`
```

2023-09-26 21:30 UTC, jim-wang-intel commented on docs_src/automated-vending-services/device_services.md
> +The `GET` call to the EdgeX MQTT device service's `inferenceHearbeat` command will act as a health-check for the Automated Vending cv inference service. It must return `200 OK` upon swiping an RFID c
fix url to intel-retail

2023-09-26 21:30 UTC, jim-wang-intel commented on docs_src/configuration.md
>      Note that this document likely does not cover EdgeX-specific configuration parameters. Application and device service SDK documentation can be found in the [EdgeX Foundry GitHub repositories](htt
```suggestion
    Note that this document likely does not cover EdgeX-specific configuration parameters. Application and device service SDK documentation can be found in the [EdgeX Foundry GitHub repositories](https://github.com/edgexfoundry) or in the [official EdgeX documentation here](https://docs.edgexfoundry.org/3.0/).
```

2023-09-26 22:20 UTC, lenny-intel requested changes

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/configuration.md
> +The simplest way to change one of the configuration values described below is via the use of environment variable overrides in the docker compose file. The value of each configuration item in a servi
You removed the `values described below` need so reference/example here.

configuration.yaml
```yaml
Driver:
  VID: "65535" # 0xFFFF
  PID: "53"    # 0x0035
```

compose file
```yaml
DRIVER_VID: "256" 
DRIVER_PID: "26"  
```

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/configuration.md
> +This reference implementation uses the [MQTT Device Service](https://github.com/edgexfoundry/device-mqtt-go) from EdgeX with custom device profiles. These device profiles YAML files are located [here
This one exists on main, so link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/configuration.md
> +The following items can be configured via `device-mqtt.environment` section of the service's [docker-compose.edgex.yml](https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/docker-compose
compose file exist on main, so like to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/modifying_source_code.md
> +After Docker builds the image (by executing the steps in [`ds-card-reader/Dockerfile`](https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ds-card-reader/Dockerfile)), proceed to the nex
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
> +    By default, the card number `0003293374` corresponds to a card in the [`ms-authentication/cards.json`](https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-authentication/cards.jso
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
> +The (altered) contents of <a href="https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-inventory/inventory.json"><code>ms-inventory/inventory.json</code></a> are contained in the <cod
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
> +The (altered) contents of <a href="https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-inventory/auditlog.json"><code>ms-inventory/auditlog.json</code></a> are contained in the <code>
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
> +By default, the ledger service has six registered accounts (accounts 1-6) for consumers. The valid accounts match the account ID's that have authorized access to the cooler through the <code>ms-authe
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
> +The (unaltered) contents of <a href="https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-ledger/ledger.json"><code>ms-ledger/ledger.json</code></a> are contained in the <code>content<
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
>  curl -X PUT -H "Content-Type: application/json" -d '{"setDoorClosed":"1"}' http://localhost:48097/api/v2/device/name/controller-board/setDoorClosed
```suggestion
curl -X PUT -H "Content-Type: application/json" -d '{"setDoorClosed":"1"}' http://localhost:48097/api/v3/device/name/controller-board/setDoorClosed
```

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
> +The (altered) contents of <a href="https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-inventory/inventory.json"><code>ms-inventory/inventory.json</code></a> are contained in the <cod
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
> +The (altered) contents of <a href="https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-inventory/auditlog.json"><code>ms-inventory/auditlog.json</code></a> are contained in the <code>
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase1.md
> +The (altered) contents of <a href="https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-ledger/ledger.json"><code>ms-ledger/ledger.json</code></a> are contained in the <code>content</c
file exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/phases/phase2.md
> +- [`cards.json`](https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-authentication/cards.json)
files exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/references.md
> +| Vending                 | `as-vending`                 | [https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/as-vending](https://github.com/intel-retail/automated-vending/blob/Edgex-3
Folders exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/references.md
> +| CV inference   | `ds-cv-inference`      | [https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ds-cv-inference](https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ds-cv-i
Folders exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/references.md
> +| Ledger         | `ms-ledger`              | [https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-ledger](https://github.com/intel-retail/automated-vending/blob/Edgex-3.0/ms-ledger)
Folders exists on main, link to main branch

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/index.md
>      | edgexfoundry/device-mqtt:2.2.0                       | Up 53 seconds     |
```suggestion
    | edgexfoundry/device-mqtt:3.0.0                      | Up 53 seconds     |
```

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/index.md
>      | edgexfoundry/support-notifications:2.2.0             | Up About a minute |
```suggestion
    | edgexfoundry/core-command:3.0.0                      | Up About a minute |
    | edgexfoundry/core-data:3.0.0                           | Up About a minute |
    | edgexfoundry/core-metadata:3.0.0                        | Up About a minute |
    | edgexfoundry/support-notifications:3.0.0                | Up About a minute |
```

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/index.md
>      | eclipse-mosquitto:2.0.14                             | Up 52 seconds     |
```suggestion
    | eclipse-mosquitto:2.0.15                             | Up 52 seconds     |
```

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/index.md
>      | edgexfoundry/consul:1.10.10                          | Up About a minute |
```suggestion
    | edgexfoundry/consul:1.15.2                          | Up About a minute |
```

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/index.md
>      | redis:6.2-alpine                                     | Up About a minute |
```suggestion
    | redis:7.0.11-alpine                                     | Up About a minute |
```

2023-09-26 22:20 UTC, lenny-intel commented on docs_src/index.md
> +The docker-compose files are segmented to allow for fine control of physical and simulated devices, as well as allowing you the choice of running Portainer. Use the [`makefile`](https://github.com/in
file exists on main. Link to main

2023-09-26 23:02 UTC, ejlee3 requested changes

2023-09-26 23:02 UTC, ejlee3 commented on docs_src/phases/phase1.md
> +The steps in this guide show how to simulate the automated Vending workflow using [`curl`](https://github.com/curl/curl) REST API calls. It is a step-by-step walkthrough with specific commands to run
```suggestion
The steps in this guide show how to simulate the Automated Vending workflow using [`curl`](https://github.com/curl/curl) REST API calls. It is a step-by-step walkthrough with specific commands to run on the command line.
```

2023-09-27 01:04 UTC, vli11 commented on docs_src/automated-vending-services/device_services.md
> +The `ds-card-reader` device service is an EdgeX device service that allows a USB-based RFID card reader to grant access to the Automated Vending. At a high level, this device service is responsible f
we do need device to be authenticated to give information to automated vending. @brian-intel what do you think?

2023-09-27 15:38 UTC, lenny-intel commented on docs_src/automated-vending-services/device_services.md
> +The `ds-card-reader` device service is an EdgeX device service that allows a USB-based RFID card reader to grant access to the Automated Vending. At a high level, this device service is responsible f
The only atuh is auth of the user. The way AV Auth works is the card is read by this service and then the Auth service validates the card number and grants/denies access to the cooler.

So maybe this is better?
```suggestion
The `ds-card-reader` device service is an EdgeX device service that allows a USB-based RFID card reader to read user's card for accessing to the Automated Vending. At a high level, this device service is responsible for discovering a specific card reader device, watching for input from that device, parsing that input, and then forwarding the input thru the EdgeX framework to the ms-authentication service which authorizes/denies access to the Automated Vending.
```

2023-09-27 15:45 UTC, lenny-intel commented on docs_src/configuration.md
> +The simplest way to change one of the configuration values described below is via the use of environment variable overrides in the docker compose file. The value of each configuration item in a servi
Right, They are not in the current as this is just an example of how to change configuration via env overrides.

2023-09-27 15:47 UTC, lenny-intel commented on docs_src/configuration.md
> -- `ResponseTopic` - Subscribe topic for the response MQTT Broker
The purpose of keeping these is an example if user wants to also change them. Please restore them in env override format.

2023-09-27 15:48 UTC, lenny-intel commented on docs_src/configuration.md
> +The following items can be configured via `device-mqtt.environment` section of the service's [docker-compose.edgex.yml](https://github.com/intel-retail/automated-vending/tree/main/docker-compose.edge
```suggestion
The following `MQTTBrokerInfo` configuration items can be configured via `device-mqtt.environment` section of the service's [docker-compose.edgex.yml](https://github.com/intel-retail/automated-vending/tree/main/docker-compose.edgex.yml) file.
```

2023-09-27 15:49 UTC, lenny-intel commented on docs_src/configuration.md
> +`device-mqtt.environment`
```suggestion
`MQTTBrokerInfo via device-mqtt.environment`
```

2023-09-27 17:52 UTC, brian-intel commented on docs_src/automated-vending-services/device_services.md
> +The `ds-card-reader` device service is an EdgeX device service that allows a USB-based RFID card reader to read user's card for accessing to the Automated Vending. At a high level, this device servic
```suggestion
The `ds-card-reader` device service is an EdgeX device service that allows a USB-based RFID card reader to read the user's card and grant access to the Automated Vending system. At a high level, this device service is responsible for discovering a specific card reader device, watching for input from that device, parsing that input, and then forwarding the input through the EdgeX framework to the ms-authentication service which authorizes/denies access to the Automated Vending.
```

2023-09-27 18:00 UTC, brian-intel approved these changes

2023-09-27 18:03 UTC, lenny-intel requested changes

2023-09-27 18:03 UTC, lenny-intel commented on docs_src/configuration.md
> +      DRIVERCONFIG__DEVICESEARCHPATH: "/dev/input/event*"
Only one underscore

```suggestion
      DRIVERCONFIG_DEVICESEARCHPATH: "/dev/input/event*"
```

2023-09-27 18:03 UTC, lenny-intel commented on docs_src/configuration.md
> +The simplest way to change one of the configuration values described below is via the use of environment variable overrides in the docker compose file. The value of each configuration item in a servi
Nothing actually described below...
```suggestion
The simplest way to change one of the service's configuration values is via the use of environment variable overrides in the docker compose file. The value of each configuration item in a service's configuration can be overridden with an environment variable specific to that item. The name of the environment variable is the path to the item in the configuration tree with underscores separating the nodes. The  environment variable name is upper case version of the setting that found in the service's configuration. These overrides are placed in the target service's environment section of the compose file. Here is an example:
```

2023-09-27 18:52 UTC, lenny-intel approved these changes
LGTM

2023-09-27 18:53 UTC, jim-wang-intel approved these changes
LGTM

2023-09-27 19:31 UTC, merged